# Generated by Django 4.0.4 on 2022-05-18 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Familiar',
        ),
    ]
