# Generated by Django 4.0.4 on 2022-05-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0002_rename_persona_familiar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='numero_documento',
        ),
        migrations.AddField(
            model_name='familiar',
            name='numero_telefono',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
