# Generated by Django 4.0.4 on 2022-05-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0003_remove_familiar_numero_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='numero_documento',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
