# Generated by Django 4.0.4 on 2022-05-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0004_familiar_numero_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
